# Generated by Django 4.1.3 on 2022-12-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=10)),
                ('dob', models.CharField(max_length=10)),
                ('designation', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='image')),
                ('desc', models.TextField()),
                ('gender', models.CharField(max_length=20)),
                ('qualification', models.CharField(max_length=30)),
            ],
        ),
    ]
