# Generated by Django 4.1.3 on 2022-12-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rollno',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
