# Generated by Django 4.1.3 on 2023-01-02 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_transaction_id_transaction_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='student',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.student'),
        ),
    ]
