# Generated by Django 4.1.3 on 2023-01-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_student_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cl',
            field=models.CharField(default='', max_length=200),
        ),
    ]
