# Generated by Django 4.1.3 on 2023-01-09 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_transaction_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('name', 'rollno', 'fname', 'mname', 'mobileno', 'dob', 'gender', 'address', 'postcode', 'image', 'cl')},
        ),
    ]
