# Generated by Django 4.1.3 on 2023-01-09 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_student_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('name', 'rollno', 'fname', 'mname', 'mobileno', 'dob', 'gender', 'address', 'postcode', 'cl')},
        ),
    ]
